version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  app1:
    build: .
    container_name: rate-limiter-app-1
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis

  app2:
    build: .
    container_name: rate-limiter-app-2
    depends_on:
      - redis
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2